version: "3"

services:
  postgres15:
    image: postgres:15.1-alpine3.17
    container_name: postgres15
    restart: always
    environment:
      POSTGRES_USER: Reoptima
      POSTGRES_PASSWORD: passwd
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5432:5432"
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: reoptima@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "8080:80"
volumes:
  db-data: