version: "3"

services:
  postgres15:
    image: postgres:15.1-alpine3.17
    container_name: postgres15
    restart: always
    environment:
      POSTGRES_USER: Reoptima
      POSTGRES_PASSWORD: passwd
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres15
volumes:
  db-data: